apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
  - name: rabbitmq-port-5672
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: rabbitmq-port-15672
    protocol: TCP
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq